# Generated by Django 4.2.4 on 2023-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_city_profile_phone_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
    ]
