# Generated by Django 4.2.4 on 2023-08-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
