# Generated by Django 4.2.4 on 2023-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usermode',
            field=models.TextField(default='customer'),
            preserve_default=False,
        ),
    ]
