# Generated by Django 4.2.4 on 2023-08-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='products',
            name='productimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='productimg'),
        ),
    ]
