# Generated by Django 4.2.4 on 2023-08-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_products_profileimg_products_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product',
        ),
    ]
