# Generated by Django 4.2.4 on 2023-08-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_products_user_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id_product',
        ),
    ]
