# Generated by Django 4.2.4 on 2023-08-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_products_id_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomndation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic', models.TextField()),
                ('cloth', models.TextField()),
                ('watches', models.TextField()),
                ('grocery', models.TextField()),
                ('sports', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
    ]
