# Generated by Django 4.2.4 on 2023-08-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_recomndation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomndation',
            new_name='Recommendation',
        ),
    ]
