# Generated by Django 4.2.4 on 2023-08-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
