# Generated by Django 4.2.4 on 2023-08-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_cartproduct_alter_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
