# Generated by Django 4.2.4 on 2023-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_cartproduct_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='description',
            field=models.TextField(default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='productimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='ratings',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
