# Generated by Django 4.2.4 on 2023-08-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cartproduct_description_cartproduct_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='productimg',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='review',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='type',
        ),
    ]
