# Generated by Django 4.2.4 on 2023-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_products_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='cleaning'),
            preserve_default=False,
        ),
    ]
